### ISSUE TITLE
NameError when using custom_attributes on python 3.6 (actually any python 3+)

### ISSUE THREAD

**Issue by tonymillion** [mParticle/mparticle-python-sdk#3]
```
>>> print(config.to_debug_report())
Python SDK Debug Report:
OS: darwin
Python Version: 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Version of the API: 0.9.1
SDK Package Version: 0.9.1
```

Creating an `AppEvent` with `custom_attributes` results in the following:

```
>>> ae = AppEvent(event_name="cat_loved",
                  custom_attributes={
                      'attr': 'cats',
                      'sub_attr': 'cat_lover',
                      'cat_uuid': '2934c008-def1-470d-8121-3f982bc7c9f7',
                  })

Traceback (most recent call last):
  File "<console>", line 6, in <module>
  File "<redacted>/mparticle/models/app_event.py", line 75, in __init__
    self.custom_attributes = custom_attributes
  File "<redacted>/mparticle/models/app_event.py", line 238, in custom_attributes
    if not mparticle.ApiClient.validate_attribute_bag_values(custom_attributes):
  File "<redacted>/mparticle/api_client.py", line 195, in validate_attribute_bag_values
    return not (custom_attributes is not None and not all(value is None or type(value) in [unicode,int,str,float,bool,long] for value in custom_attributes.values()))
  File "<redacted>/mparticle/api_client.py", line 195, in <genexpr>
    return not (custom_attributes is not None and not all(value is None or type(value) in [unicode,int,str,float,bool,long] for value in custom_attributes.values()))
NameError: name 'unicode' is not defined
```

Defining `unicode` like `unicode=str` then results in the same exception except `long` is not defined (`unicode` and `long` are not valid in python 3)

**Comment by samdozor** [comment]
thanks for noting this @tonymillion . We can probably relax this check or otherwise make it more dynamic to avoid referencing those types

**Comment by tonymillion** [comment]
Six defines the relevant string and number types you can use for comparisons and still maintain platform compatibility

**Comment by samdozor** [comment]
Addressed by https://github.com/mParticle/mparticle-python-sdk/pull/4
